# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true
    
    http_client:
        default_options:
            headers:
                'x-rapidapi-host': '%env(RAPIDAPI_HOST)%'
                'x-rapidapi-key': '%env(RAPIDAPI_KEY)%'
        scoped_clients:
            api.football:
                base_uri: 'https://api-football-v1.p.rapidapi.com'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
